"""Initial migration

Revision ID: 358b152ed7d9
Revises: 
Create Date: 2024-03-28 15:59:26.698234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358b152ed7d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
